namespace Network.Packets.Client
{
    /// <summary>
    /// This has all packet types
    /// </summary>
    public enum ClientPacketType : byte
    {
        ProtocolVersion = 0x00,
        ValidateClient = 0x01,
        ConnectClient = 0x03,
        ConnectSwitch = 0x04,
        SwitchSever = 0x05,
        ServerTime = 0x06,
        Message = 0x07,
        Log = 0x08,
        SyncMoney = 0x0c,
        FactoryModifyUnit = 0x11,
        FactoryModifyEnd = 0x12,
        IsValidName = 0x16,
        FactoryChangeUnitName = 0x17,
        RequestInventory = 0x18,
        RequestSearchGame = 0x19,
        CreateGame = 0x1b,
        EnterGame = 0x1c,
        ListUser = 0x1f,
        Ready = 0x20,
        Exit = 0x21,
        StartGame = 0x22,
        SelectBase = 0x2b,
        ReadyGame = 0x2c,
        RequestPalette = 0x2e,
        MoveUnit = 0x2f,
        AimUnit = 0x30,
        StartAttack = 0x31,
        StopAttack = 0x32,
        RequestRegain = 0x35,
        ModeSniper = 0x38,
        UseSkill = 0x39,
        RequestChangeWeaponSet = 0x3a,
        RequestQuitBattle = 0x3b,
        BuyList = 0x3f,
        RequestGoodsData = 0x40,
        RequestAvatarInfo = 0x46,
        RequestStatsTraining = 0x47,
        RequestStatsSurvival = 0x48,
        RequestStatsTeamSurvival = 0x49,
        RequestStatsTeamBattle = 0x4a,
        RequestStatsCtf = 0x4b,
        RequestStatsClanBattle = 0x4c,
        RequestStatsDefensiveBattle = 0x4d,
        RequestBestInfo = 0x4e,
        TutorialSelect = 0x57,
        UnAimUnit = 0x5a,
        MsgConnect = 0x63,
        MsgUserStateInfo = 0x64,
        MsgUserClanInfo = 0x66,
        MsgGetBuddyList = 0x67,
        MsgGetChannelList = 0x69,
        MsgJoinChannel = 0x6a,
        MsgLeaveChannel = 0x6b,
        MsgChannelChatting = 0x6c,
        RequestOperator = 0x71,
        SelectOperator = 0x72
    }
}